version: "3.9"

services:
  redis:
    image: redis
    restart: always
    # deploy:
    #   resources:
    #     limits:
    #       cpus: ${REDIS_CPUS:-0.125} 
    #       memory: ${REDIS_MEM:-1G}
  
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - APP_DB_NAME=webhw3

    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    
    ports:
      - 5432:5432

  client:
    build: ./client
    ports:
      - 8000:80
    depends_on:
      - server

  server:
    build: ./server
    depends_on:
      - redis
      - database
      # - cache
    
    command: su -c "yarn migrate && yarn start"


  # cache:
  #   build: ./cache
  #   deploy:
  #     replicas: ${GO_REPLICAS:-1}
  #     resources:
  #       limits:
  #           cpus: ${GO_CPUS:-0.125} 
  #           memory: ${GO_MEM:-100M}
  #       reservations:
  #         cpus: ${GO_CPUS_RES:-0.125} 
  #         memory: ${GO_MEM_RES:-50M}

